In [14]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
import pandas as pd

In [15]:
df=pd.read_csv('../data/basket_analysis.csv')
df.head()

,Unnamed: 0,Apple,Bread,Butter,Cheese,Corn,Dill,Eggs,Ice cream,Kidney Beans,Milk,Nutmeg,Onion,Sugar,Unicorn,Yogurt,chocolate
0,0,False,True,False,False,True,True,False,True,False,False,False,False,True,False,True,True
1,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
2,2,True,False,True,False,False,True,False,True,False,True,False,False,False,False,True,True
3,3,False,False,True,True,False,True,False,False,False,True,True,True,False,False,False,False
4,4,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [16]:
df = df.drop('Unnamed: 0', axis=1)
df.head()

,Apple,Bread,Butter,Cheese,Corn,Dill,Eggs,Ice cream,Kidney Beans,Milk,Nutmeg,Onion,Sugar,Unicorn,Yogurt,chocolate
0,False,True,False,False,True,True,False,True,False,False,False,False,True,False,True,True
1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
2,True,False,True,False,False,True,False,True,False,True,False,False,False,False,True,True
3,False,False,True,True,False,True,False,False,False,True,True,True,False,False,False,False
4,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [17]:
df_encoded = df.applymap(lambda x: 1 if x else 0)

C:\Users\drnim\AppData\Local\Temp\ipykernel_13524\850912994.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_encoded = df.applymap(lambda x: 1 if x else 0)

In [19]:
df_encoded.head()

,Apple,Bread,Butter,Cheese,Corn,Dill,Eggs,Ice cream,Kidney Beans,Milk,Nutmeg,Onion,Sugar,Unicorn,Yogurt,chocolate
0,0,1,0,0,1,1,0,1,0,0,0,0,1,0,1,1
1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
2,1,0,1,0,0,1,0,1,0,1,0,0,0,0,1,1
3,0,0,1,1,0,1,0,0,0,1,1,1,0,0,0,0
4,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [20]:
# Apply the Apriori algorithm to find frequent itemsets with a lower minimum support (0.2)
frequent_itemsets = apriori(df_encoded, min_support=0.2, use_colnames=True)

# Check if frequent_itemsets is empty
if frequent_itemsets.empty:
    print("No frequent itemsets found. Try lowering the min_support threshold.")
else:
    # Generate association rules from the frequent itemsets with a minimum lift of 1
    rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1, num_itemsets=2)

    # Display the resulting rules
    print(rules)

       antecedents     consequents  antecedent support  consequent support  \
0         (Butter)     (Ice cream)            0.420420            0.410410
1      (Ice cream)        (Butter)            0.410410            0.420420
2   (Kidney Beans)        (Butter)            0.408408            0.420420
3         (Butter)  (Kidney Beans)            0.420420            0.408408
4         (Butter)     (chocolate)            0.420420            0.421421
5      (chocolate)        (Butter)            0.421421            0.420420
6   (Kidney Beans)        (Cheese)            0.408408            0.404404
7         (Cheese)  (Kidney Beans)            0.404404            0.408408
8      (Ice cream)     (chocolate)            0.410410            0.421421
9      (chocolate)     (Ice cream)            0.421421            0.410410
10          (Milk)     (chocolate)            0.405405            0.421421
11     (chocolate)          (Milk)            0.421421            0.405405

     support  confidence      lift  representativity  leverage  conviction  \
0   0.207207    0.492857  1.200889               1.0  0.034662    1.162571
1   0.207207    0.504878  1.200889               1.0  0.034662    1.170579
2   0.202202    0.495098  1.177626               1.0  0.030499    1.147905
3   0.202202    0.480952  1.177626               1.0  0.030499    1.139764
4   0.202202    0.480952  1.141262               1.0  0.025028    1.114693
5   0.202202    0.479810  1.141262               1.0  0.025028    1.114169
6   0.200200    0.490196  1.212143               1.0  0.035038    1.168284
7   0.200200    0.495050  1.212143               1.0  0.035038    1.171583
8   0.202202    0.492683  1.169098               1.0  0.029246    1.140467
9   0.202202    0.479810  1.169098               1.0  0.029246    1.133412
10  0.211211    0.520988  1.236263               1.0  0.040365    1.207857
11  0.211211    0.501188  1.236263               1.0  0.040365    1.192021

    zhangs_metric   jaccard  certainty  kulczynski
0        0.288629  0.332263   0.139837    0.498868
1        0.283728  0.332263   0.145722    0.498868
2        0.254963  0.322684   0.128848    0.488025
3        0.260247  0.322684   0.122625    0.488025
4        0.213564  0.316119   0.102892    0.480381
5        0.213933  0.316119   0.102470    0.480381
6        0.295838  0.326797   0.144043    0.492623
7        0.293849  0.326797   0.146454    0.492623
8        0.245323  0.321145   0.123167    0.486246
9        0.249991  0.321145   0.117708    0.486246
10       0.321413  0.343089   0.172088    0.511088
11       0.330310  0.343089   0.161088    0.511088

C:\Users\drnim\AppData\Local\Programs\Python\Python312\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [21]:
rules=rules[['antecedents','consequents','support','confidence','lift']]
rules.head(25)

       antecedents     consequents   support  confidence      lift
0         (Butter)     (Ice cream)  0.207207    0.492857  1.200889
1      (Ice cream)        (Butter)  0.207207    0.504878  1.200889
2   (Kidney Beans)        (Butter)  0.202202    0.495098  1.177626
3         (Butter)  (Kidney Beans)  0.202202    0.480952  1.177626
4         (Butter)     (chocolate)  0.202202    0.480952  1.141262
5      (chocolate)        (Butter)  0.202202    0.479810  1.141262
6   (Kidney Beans)        (Cheese)  0.200200    0.490196  1.212143
7         (Cheese)  (Kidney Beans)  0.200200    0.495050  1.212143
8      (Ice cream)     (chocolate)  0.202202    0.492683  1.169098
9      (chocolate)     (Ice cream)  0.202202    0.479810  1.169098
10          (Milk)     (chocolate)  0.211211    0.520988  1.236263
11     (chocolate)          (Milk)  0.211211    0.501188  1.236263

In [22]:
# Filter rules with lift greater than 1.2
rules_filtered = rules[rules['lift'] > 1.2]

# Display the filtered rules
print(rules_filtered)

       antecedents     consequents   support  confidence      lift
0         (Butter)     (Ice cream)  0.207207    0.492857  1.200889
1      (Ice cream)        (Butter)  0.207207    0.504878  1.200889
6   (Kidney Beans)        (Cheese)  0.200200    0.490196  1.212143
7         (Cheese)  (Kidney Beans)  0.200200    0.495050  1.212143
10          (Milk)     (chocolate)  0.211211    0.520988  1.236263
11     (chocolate)          (Milk)  0.211211    0.501188  1.236263

In [26]:
# Filter rules with support greater than 1.2
rules_filtered = rules[rules['support'] > 0.2]

# Display the filtered rules
print(rules_filtered)

       antecedents     consequents   support  confidence      lift
0         (Butter)     (Ice cream)  0.207207    0.492857  1.200889
1      (Ice cream)        (Butter)  0.207207    0.504878  1.200889
2   (Kidney Beans)        (Butter)  0.202202    0.495098  1.177626
3         (Butter)  (Kidney Beans)  0.202202    0.480952  1.177626
4         (Butter)     (chocolate)  0.202202    0.480952  1.141262
5      (chocolate)        (Butter)  0.202202    0.479810  1.141262
6   (Kidney Beans)        (Cheese)  0.200200    0.490196  1.212143
7         (Cheese)  (Kidney Beans)  0.200200    0.495050  1.212143
8      (Ice cream)     (chocolate)  0.202202    0.492683  1.169098
9      (chocolate)     (Ice cream)  0.202202    0.479810  1.169098
10          (Milk)     (chocolate)  0.211211    0.520988  1.236263
11     (chocolate)          (Milk)  0.211211    0.501188  1.236263

Antecedents: The items on the left-hand side of the rule (e.g., Butter).
Consequents: The items on the right-hand side of the rule (e.g., Ice cream).
Support: The proportion of transactions that contain both the antecedents and consequents.
Confidence: The probability of finding the consequent given the antecedent.
Lift: A measure of how much more likely the consequent is given the antecedent compared to random chance.
Leverage: The difference between the observed support and the expected support if the antecedents and consequents were independent.
Conviction: A measure of how likely the rule is to be true compared to a random chance.
Other metrics: Zhang's Metric, Jaccard, Certainty, Kulczynski, and more.

In [ ]:
# END